### ISSUE TITLE
Design docs

### ISSUE THREAD

**Issue by charifmews** [Vrijheid-Zonder-Maar/vzm-frontend#9]
Creating a document where the style rules are defined (specific color-codes, fonts etc). Prefer markdown documents (.md), but any other option will do and will otherwise convert it. @andreaspeijer (don't overthink it, just write which things you are sure of and maybe would like (like thenewyorker style layout desktop)). After your version, will complete/change the document and propose it to the three of us (so that we are all happy with the style decisions )

**Comment by andreaspeijer** [comment]
colors website| Style templates
------------ | -------------
Red, black, blue and white. No more to prevent confusion. Adhere to the current division between colors of headers, topics, links and text. | TheNewYorker, Medium, The Daily Beast. Clean reading experience with a bit of flair [we use Cynzel Decorative for that purpose and the red for all html headers.].
other things| other things
------------ | -------------
not sure yet | not sure yet

**Comment by charifmews** [comment]
Updated the [wiki](https://github.com/Vrijheid-Zonder-Maar/vzm-frontend/wiki) and it's enough for the basic version (except layout homepage/article, but will be later determined when the API is clear)
